name: Release Chart
on:
  push:
    branches:
      - main
    paths: 
      - "deploy/helm-chart/**"
      - "README.md"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@master
        with:
          charts_dir: deploy/helm-chart
          linting: off
          token: ${{ secrets.GH_TOKEN }}
